branch-defaults:
  wpm:
    environment: wrtc9
environment-defaults:
  wrtc-node:
    branch: null
    repository: null
global:
  application_name: wrtc-ph
  default_ec2_keyname: wpmd
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.3.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
